learning_site/courses/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)$', views.step_detail, name='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/learn_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title      = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title  = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    orderd = models.IntegerField(default=0)
    course = models.ForeignKey(Course, related_name='steps')

    class Meta:
        ordering = ['orderd',]


    def __str__(self):
        return self.title

learning_site/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Course,Step


def course_list(request):
    courses = Course.objects.all()
    email = 'questions@learning_site.com'
    return render(request, 'courses/course_list.html', {'courses': courses , 'email': email})

def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/learn_django/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, 'home.html')

learning_site/courses/templates/courses/course_detail.html
{% extends 'layout.html' %}
{% load humanize %}
{% load course_extras %}

{% block title %} {{ course.title }} {% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description|markdown_to_html }}


    <p> There are {{ course.steps.count|apnumber }} step{{ course.steps.count|pluralize }} in the course: {{ course.steps.all|join:", " }} </p>

    <section>
        {% for step in course.steps.all %}
            <h3>
                <a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a>
            </h3>
            {{ step.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}

{% block title %} Available courses {% endblock %}

{% block content %}
<div class="cards">
    {% for course in courses %}
    <div class="card">
        <header>
            <a href="{% url 'courses:detail' pk=course.pk %}">{{course.title}}</a>
        </header>
        <div class="card-copy">
            {% if course.description|wordcount <= 5 %}
                {{course.description}}
            {% else %}
                {{ course.description|truncatewords:5 }}
                <a href="{% url 'courses:detail' pk=course.pk %}">Read more</a>
            {% endif %}
            <div>
                Created on: {{ course.created_at|date:"d/m/y" }}
            </div>
        </div>
    </div>
    <div>
        Have questions? Contact us! {{ email|urlize }}
    </div>
    {% endfor %}
</div>


{% endblock %}

learning_site/courses/templates/courses/course_nav.html
{% for course in courses %}
    <div>
        <a href="{%  url 'courses:detail' pk=course.pk %}">{{course.title}}</a>
    </div>
{% endfor %}

learning_site/courses/templates/courses/step_detail.html
{% extends 'layout.html' %}
{% load course_extras %}

{% block title %} {{ step.title}} {% endblock %}

{% block content %}
<article>
    <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
    <h3>{{ step.title }}</h3>
    {% with con=step.content %}
        {{ con|linebreaks }} Content: {{ con|wordcount }} words.
        Estimated time to complete: {{  con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}.
    {% endwith %}
</article>

{% endblock %}

learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %} Well hello there! {% endblock %}

{% block content %}
<h1>Wellcome!</h1>
{% endblock %}

learning_site/templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        {% block static %}  {% endblock %}
    </head>
    <body>
        <div class="site-container">
            <div>{%  nav_courses_list %}</div>
            <nav>
                <a href="{% url 'index' %}">Home</a>
                <a href="{% url 'courses:list' %}">Courses</a>
            </nav>
            <p>Don't miss our latest course, {% newest_course %}!</p>
            {% block content %} {% endblock %}
        </div>
    </body>
</html>